name: Publish Writerside Docs to GitHub Pages

on:
  push:
    branches:
      - master   # update if your default branch is different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Writerside docs
        uses: JetBrains/writerside-github-action@v4
        with:
          instance: "Writerside/infinity"
          artifact: "webHelpINFINITY2-all.zip"
          location: "Writerside"

      - name: Unzip artifact
        run: unzip -q artifacts/webHelpINFINITY2-all.zip -d webHelpINFINITY2

      - name: Copy custom CSS and font files
        run: |
          cp Writerside/cfg/custom.css webHelpINFINITY2/custom.css
          cp Writerside/cfg/Uncut-Sans.woff2 webHelpINFINITY2/Uncut-Sans.woff2

      - name: Inject custom CSS into HTML files
        run: |
          for file in webHelpINFINITY2/*.html; do
            sed -i 's|</head>|<link rel="stylesheet" href="custom.css"></head>|' "$file"
          done


      - name: Upload artifact to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: "webHelpINFINITY2"   # Folder inside the produced ZIP

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4